spring:
  application:
    name: "banking-app"
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=600s
  datasource:
    url: jdbc:postgresql://localhost:5430/banking_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true

  #jwt
jwt:
  secret: 8074658237c236e39e96e909ac1abb25a3e1773b100096ad6877c439cd452c17
  expiration: 6000000
  header: Authorization

#  swagger
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html